Generate site
svsticky/pxl pull request #20
Opened 2018-11-27 21:13 UTC by duijf

This PR adds static site generation based on the S3 stored state.

Contents:

 - Generate static site output based on S3 state
 - Rename HTML files in the `design` directory, convert to Jinja2, parameterize
 - Remove example images
 - Move assets to own directories
 - Catch some `boto3` exceptions that I ran into when testing

2018-11-27 22:38 UTC, HugoPeters1024 requested changes
Please clarify the created locale comments, besides that it looks great!

2018-11-27 22:38 UTC, HugoPeters1024 commented on pxl/state.py
> +    def created_human(self):
why the specific `human`? I assume that this refers to the timestamp it was created? Also it is not self evident to me what threadsafe issues have to do with this.

2018-11-27 22:38 UTC, HugoPeters1024 commented on pxl/generate.py
> +    index_template = load_template(template_dir / 'index.html.j2')
wut? this 4 real? pretty neat

2018-12-11 17:38 UTC, duijf commented on pxl/generate.py
> +    index_template = load_template(template_dir / 'index.html.j2')
Yes

2018-12-11 17:39 UTC, duijf commented on pxl/state.py
> +    def created_human(self):
I gave it this name because it is the timestamp for human consumption

The threadsafety stuff is just me ranting

2018-12-11 17:44 UTC, merged